line-length = 100
target-version = "py312"
exclude = ["old-scripts-for-reference-only", "scripts"]

[lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"